# Generated by Django 4.0.4 on 2022-08-27 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureHistory',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('lecture_name', models.CharField(max_length=255)),
                ('lecture_url', models.CharField(max_length=255)),
                ('embed_url', models.CharField(max_length=255)),
                ('id_url', models.CharField(max_length=255)),
                ('lecture_note', models.TextField()),
                ('lecture_sum', models.TextField()),
                ('keyword', models.TextField()),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
